### ISSUE TITLE
Second hotbar cuts main hotbar's texture + suggestion

### ISSUE THREAD

**Issue by Desempregago** [gudenau/minecraft-largebar#5]
![image](https://user-images.githubusercontent.com/14002834/117921608-6654c680-b2c7-11eb-9d9b-899857db5121.png)
Suggestion: Add a 1 pixel gap between the hotbars so this doesn't happen ^

**Comment by Desempregago** [comment]
ps: v1.1.0

**Comment by Desempregago** [comment]
And apparently, the second hotbar's contents are 1 pixel LOWER than the texture suggests, overlapping with the hotbar overlay
![image](https://user-images.githubusercontent.com/14002834/117922019-26421380-b2c8-11eb-8264-2644ddd760eb.png)

**Comment by gudenau** [comment]
Adding an addition pixel gap to this would make it so there's either a strip of repeating texture or a black bar in the middle.

**Comment by Bluberry-Kat** [comment]
i couldn't reproduce the overlay rendering error in my own modpack. 
@Fogrits can you share your modlist? i believe this is a bug that only occurs in the presence of another mod

**Comment by Desempregago** [comment]
I'm suspecting it may be more of a Bedrockify issue rather than LargeBar.

**Comment by Desempregago** [comment]
I'm closing the issue for now. If I run into more problems, I'll come back to report.
